### ISSUE TITLE
postgres-ha or postgres-flex?

### ISSUE THREAD

**Issue by viggy28** [fly-apps/postgres-flex#116]
I see there is already [postgres-ha](https://github.com/fly-apps/postgres-ha) which provides Postgres HA. 

So which one is recommended way to run Postgres HA in fly?

**Comment by davissp14** [comment]
@viggy28 Some additional context is provided here: https://community.fly.io/t/improved-postgres-clustering-with-repmgr-preview/10668

In short, this is the next iteration of our Postgres offering and will be made the new default very soon.

**Comment by davissp14** [comment]
This project has been made the new default PG implementation as of flyctl `v0.0.463`.  Please follow the thread provided above for additional details.
