### ISSUE TITLE
SSL certificates through letsencrypt

### ISSUE THREAD

**Issue by owenthereal** [fly-apps/postgres-flex#219]
It would be nice if I would be able to connect to the pg instance externally with an SSL certificate through lets-encrypt.

**Comment by owenthereal** [comment]
https://github.com/fly-apps/postgres-ha/issues/4 may be related but it's for fly-apps/postgres-ha

**Comment by benwaffle** [comment]
Doesn't fly-proxy support postgres over tls? https://fly.io/docs/postgres/connecting/connecting-external/

**Comment by owenthereal** [comment]
Correct. Closing.
