### ISSUE TITLE
Consider replacing cron with supercronic

### ISSUE THREAD

**Issue by LeoAdamek** [fly-apps/postgres-flex#227]
As per [Fly's docs](https://fly.io/docs/blueprints/supercronic/)  -- Standard system cron daemons aren't very suited to container-based environments. Primarily because they clear the env to prevent disseminating secrets. 

However this means that some barman features just don't quite work right, such as using `barman-cloud-wal-archive` as a pre-archive script hook to automatically relay WALs to external storage.  It'd be great if supercronic shipped in the image for this purpose, and the `start` command would use this instead. 

Currently my workaround is to add the `pre_archive` script to my barman.conf manually and manually download and run supercronic via `nohup` so as not to need modification to the container image. 

If a PR is wanted, I could look at it next week I think.

**Comment by davissp14** [comment]
@LeoAdamek  Just an fyi, we are looking to deprecate the separate barman machine in favor of running archiving next to the primary, which should simplify on-going management.  

Some early details can be found here: https://github.com/fly-apps/postgres-flex/pull/231
