### ISSUE TITLE
Configure Postgres to accept external connections  

### ISSUE THREAD

**Issue by Pedromigacz** [fly-apps/postgres-flex#259]
## Issue
It's not possible to create an external connection using `fly postgres`.
Thus, the docs instructions on this matter are broken.

## Proposal
Postgres `listen_addresses` property should be, by default, `*`.
The docs should be updated to match the new behavior. Creating an external connection would take 5 minutes if this is done.

### Why?
1. This won't affect people trying to use postgres on the internal networking system (`listen_addresses` is already `*` on `postgresql.internal.conf`).
2. By default, a machine/app generate from this image would be already fully private, as it won't have public ips.
3. If you are adding an external ip to your project, you already have intentions of exposing it to the internet.
4. This project is the origin of a stand alone Postgres image, and cannot be used in a single machine together with another project, thus it won't affect another project by listening on the same ports as them.

**Comment by Pedromigacz** [comment]
I will create a PR tomorrow fixing this and if approved, I can even update  the docs.
This [post](https://community.fly.io/t/i-cant-establish-an-external-connection-to-my-brand-new-fly-postgres-app/21356/10), created by myself, is why I want to fix this issue.

**Comment by davissp14** [comment]
We already default `listen_addresses = '*'`.  I have also confirmed that external connections can be made via `<app-name>.fly.dev` in both PG 15/16. 

Some information that would be helpful:

1. Your image details `fly image show`.
2. Confirm that you have a public `global` ip address bound to your app.  You can view this via `fly ips list`. 
3. Please specify/list any errors you are encountering.

**Comment by Pedromigacz** [comment]
You are correct. I was writing the steps to reproduce and just learned that `<app-name>.fly.dev` does become reachable once you have a public ipv4 enabled (and probably once you have a public ipv6 enabled as well, I just don't have a way to test it nor know how to enable it on my machine).
Sorry for the misleading issue.
I think the documentation on this could be improved. I will try to make a PR there.

**Comment by Pedromigacz** [comment]
You are correct. I was writing the steps to reproduce and just learned that <app-name>.fly.dev does become reachable once you have a public ipv4 enabled (and probably once you have a public ipv6 enabled as well, I just don't have a way to test it nor know how to enable it on my machine).
Sorry for the misleading issue.
I think the documentation on this could be improved. I will try to make a PR there.
