### ISSUE TITLE
How to enable slow query 

### ISSUE THREAD

**Issue by kubosuke** [fly-apps/postgres-flex#262]
# Overview

We'd like to enable slow query to analyze db performance with pghero

# Description

we'd like to use pghero to analyze postgres performance, but on db, we need to configure it to enable slow query:

<img width="640" alt="image" src="https://github.com/user-attachments/assets/dcd877ca-418f-4642-8960-43bf3413c0ba">

how can we achieve it?

# Expected outcomes

enable slow query, or update `postgresql.conf` as below

```
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
```

**Comment by kubosuke** [comment]
I found configuration under `/data/postgresql/postgresql.conf` , but not sure is it okay to update it directly, or is there a way to inject config when starting up container? 🤔

**Comment by davissp14** [comment]
You can enable `pg_stat_statements` through flyctl. 

```
fly pg config update --shared-preload-libraries 'repmgr,pg_stat_statements' --app <app-name>
```

**Comment by kubosuke** [comment]
thanks it works!
