### ISSUE TITLE
Support repmgr witness

### ISSUE THREAD

**Issue by davissp14** [fly-apps/postgres-flex#34]
The witness is a lightweight component that acts as a voting member in a given cluster.  It doesn't hold user-data, it's only purpose is to act as a stand-in so quorum can be met.

As an example, say we have a 2 member setup running witin the same region.

Node A ( primary )
Node B

If Node B goes down, we have to assume a potential network partition and turn the primary read-only.   

This is where the witness comes in:

Node A ( primary )
Node B
Node C ( witness )

If Node B goes down, we can continue functioning as we can now interact with the majority of the cluster.

**Why would I run a Witness over a 3rd member**

You should probably just run a 3rd member.  The witness is really just a budget friendly way to achieve HA.

**Comment by guillaumervls** [comment]
Being worked on in https://github.com/fly-apps/postgres-flex/pull/174
